export const data = {
  equity: {
    canadianEquity: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    usEquity: {
      hiring: true,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    internationalEquity: {
      hiring: false,
      definedBenefit: 1.2,
      definedContribution: 1.5,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    emergingMarketsEquity: {
      hiring: true,
      definedBenefit: 1.2,
      definedContribution: 1.5,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    globalEquity: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    equityUndefined: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    equityOther1: {
      title: "Other 1",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    equityOther2: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    equityOther3: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
  },
  bonds: {
    canadianBonds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    usBonds: {
      hiring: true,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    internationalBonds: {
      hiring: false,
      definedBenefit: 1.2,
      definedContribution: 1.5,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    realReturnBonds: {
      hiring: true,
      definedBenefit: 1.2,
      definedContribution: 1.5,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    highYieldBonds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    emergingMarketsDebt: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    BondsUndefined: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    bondsOther1: {
      title: "Other 1",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    bondsOther2: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    bondsOther3: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
  },
  cashShortTerm: {
    cash: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    GIC: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    shortTermInstruments: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
  },
  alternatives: {
    commodities: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    hedgeFunds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    privateEquity: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    realEstate: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    infrastructure: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    derivatives: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    privateDebt: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    mortgages: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    managedFutures: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    businessTrusts: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    nonMarketableGovtDebt: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    alternativesOther1: {
      title: "Other 1",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    alternativesOther2: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    alternativesOther3: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    alternativesUndefined: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
  },
  others: {
    balancedAssetAllocationFunds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    targetDateFunds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    targetRiskFunds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    exchangeTradedFunds: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    realEstateEquity: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    infrastructureEquity: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    REITs: {
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    othersOther1: {
      title: "Other 1",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    othersOther2: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
    othersOther3: {
      title: "",
      hiring: false,
      definedBenefit: 0,
      definedContribution: 0,
      hybrid: 0,
      groupRRSP: 0,
      other: 0,
    },
  },
};
